{% set name = "vw-executor" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vw-executor-{{ version }}.tar.gz
    sha256: e6d1ae5c8735ef838ffd592a5561ada5f5e215b683347e9ac8ece7949f4331ec
  - url: https://raw.githubusercontent.com/VowpalWabbit/data-science/master/LICENSE.txt
    fn: LICENSE.txt
    sha256: c66cc3b0905f9b3da5162ef22b0aa1925dbc13603cdf012d9e0109a034155f1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas >=1.0.0
    - python >=3.6
    - tqdm >=4.0.0
    - vowpalwabbit >=8.10.0

test:
  imports:
    - vw_executor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VowpalWabbit/data-science
  summary: Helpers for driving vw execution from python
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
